version:  "3"
services:
  datascience-notebook:
      image:  jupyter/datascience-notebook
      environment:
        - JUPYTER_ENABLE_LAB=yes
      volumes:
        - .:/home/jovyan
      ports:
        - 8888:8888
      container_name:   datascience-notebook-container

